# Generated by Django 5.1.3 on 2024-11-15 05:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('memberid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('emailmain', models.EmailField(default='example@gmail.com', max_length=255, unique=True)),
                ('accountname', models.CharField(default='default_value', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters are allowed, without space', regex='^[a-zA-Z]+$')])),
                ('password', models.CharField(max_length=30)),
                ('ktpname', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('firstname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('middlename', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('lastname', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('memberstatus', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Members',
                'db_table': 'member',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('usermail', models.EmailField(default='example@gmail.com', max_length=255, unique=True)),
                ('usergroup', models.CharField(max_length=1)),
                ('usergrade', models.IntegerField(blank=True, default='')),
                ('userdesc', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Memberdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('callsign', models.CharField(blank=True, default='', max_length=25, validators=[django.core.validators.RegexValidator(message='Only letters and spaces are allowed', regex='^[a-zA-Z\\s]+$')])),
                ('participant', models.IntegerField()),
                ('instructor', models.IntegerField()),
                ('author', models.IntegerField()),
                ('referral', models.IntegerField()),
                ('dob', models.DateField()),
                ('ktpnumber', models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d+$')])),
                ('taxid', models.CharField(blank=True, default='', max_length=30, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d+$')])),
                ('join_date', models.DateField()),
                ('emailmain', models.EmailField(max_length=50)),
                ('emailalt', models.EmailField(blank=True, default='', max_length=50)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d+$')])),
                ('phone', models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers are allowed', regex='^\\d+$')])),
                ('telegram', models.CharField(blank=True, default='', max_length=20)),
                ('referralid', models.CharField(blank=True, default='', max_length=15)),
                ('paidclass', models.PositiveIntegerField(default=0, null=True)),
                ('freeclass', models.PositiveIntegerField(default=0, null=True)),
                ('pointtotal', models.PositiveIntegerField(db_column='pointTotal', default=0, null=True)),
                ('pointredeem', models.PositiveIntegerField(db_column='pointRedeem', default=0, null=True)),
                ('memberid', models.OneToOneField(db_column='memberid', null=True, on_delete=django.db.models.deletion.CASCADE, to='account.member')),
            ],
            options={
                'verbose_name_plural': 'Member Detail',
                'db_table': 'memberdetail',
                'managed': True,
                'unique_together': {('ktpnumber', 'emailmain')},
            },
        ),
    ]
