# Generated by Django 5.1.3 on 2024-11-25 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vanue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vanuename', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=250)),
                ('vanueurl', models.URLField(blank=True, null=True)),
                ('vanuegmap', models.URLField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('photo', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'vanue',
            },
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('courseid', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('coursename', models.CharField(db_index=True, max_length=100)),
                ('coursedesc', models.CharField(blank=True, max_length=200, null=True)),
                ('submission', models.DateTimeField(auto_now_add=True)),
                ('paidrun', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('freerun', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('folder', models.CharField(blank=True, max_length=250, null=True)),
                ('thumbnailurl', models.URLField(blank=True, null=True)),
                ('courselab', models.BooleanField()),
                ('labdesc', models.CharField(blank=True, max_length=250, null=True)),
                ('landingpage', models.CharField(blank=True, max_length=250, null=True)),
                ('marketingtoolkit', models.CharField(blank=True, max_length=250, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creators', to='account.member')),
            ],
            options={
                'db_table': 'coursematerial',
            },
        ),
        migrations.CreateModel(
            name='Certifiedinstructor',
            fields=[
                ('instructor', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseid_instructor', to='course.coursematerial')),
            ],
            options={
                'db_table': 'certifiedinstructor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Certifiedassistant',
            fields=[
                ('assistant', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courseid_assistant', to='course.coursematerial')),
            ],
            options={
                'db_table': 'certifiedassistant',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LookUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lookkey', models.CharField(max_length=3)),
                ('lookcode', models.CharField(max_length=30)),
                ('lookname', models.CharField(max_length=100)),
                ('lookdesc', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'lookup',
                'managed': True,
                'constraints': [models.UniqueConstraint(fields=('lookkey', 'lookcode'), name='combouniq_lookup')],
            },
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='category',
            field=models.ForeignKey(blank=True, limit_choices_to={'lookkey': 'BE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='course.lookup'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='coursetype',
            field=models.ForeignKey(blank=True, limit_choices_to={'lookkey': 'BA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coursetype', to='course.lookup'),
        ),
        migrations.AddField(
            model_name='coursematerial',
            name='languages',
            field=models.ForeignKey(blank=True, limit_choices_to={'lookkey': 'AA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='languages', to='course.lookup'),
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('classid', models.CharField(max_length=9, primary_key=True, serialize=False)),
                ('classname', models.CharField(blank=True, max_length=100, null=True)),
                ('classcity', models.CharField(blank=True, max_length=30, null=True)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('classdesc', models.TextField(blank=True, null=True)),
                ('publishrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bottomrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('suggestrate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('studentmax', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('studentjoin', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('registurl', models.URLField(blank=True, null=True)),
                ('certificateurl', models.URLField(blank=True, null=True)),
                ('competenceurl', models.URLField(blank=True, null=True)),
                ('pretask', models.URLField(blank=True, null=True)),
                ('zoomlink', models.URLField(blank=True, null=True)),
                ('classphoto', models.URLField(blank=True, null=True)),
                ('assistant1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant1', to='course.certifiedassistant')),
                ('assistant2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant2', to='course.certifiedassistant')),
                ('assistant3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assistant3', to='course.certifiedassistant')),
                ('classpic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userid_classpic', to='account.users')),
                ('presenter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presenter', to='course.certifiedinstructor')),
                ('courseid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.coursematerial')),
                ('classstatus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_status', to='course.lookup')),
                ('classtype', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_type', to='course.lookup')),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='currency', to='course.lookup')),
                ('deliverymode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_mode', to='course.lookup')),
                ('vanue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='course.vanue')),
            ],
            options={
                'db_table': 'class',
                'managed': True,
            },
        ),
        migrations.AddConstraint(
            model_name='certifiedinstructor',
            constraint=models.UniqueConstraint(fields=('courseid', 'instructor'), name='combouniq_courseid_instructor'),
        ),
        migrations.AddConstraint(
            model_name='certifiedassistant',
            constraint=models.UniqueConstraint(fields=('courseid', 'assistant'), name='combouniq_courseid_assistant'),
        ),
    ]
