# Generated by Django 5.1.3 on 2024-11-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_draftbooking_payment_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
