# Generated by Django 5.1.3 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_event_event_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftbooking',
            name='referral_name',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True),
        ),
    ]
